### ISSUE TITLE
Issue Installing generator on OS X 

### ISSUE THREAD

**Issue by LanceEa** [OfficeDev/generator-office#103]
I'm getting an error when trying to install the yo generator on OSx.
I run `sudo npm i -g generator-office` and I get the error below.

<img width="572" alt="screen shot 2015-11-11 at 10 53 12 pm" src="https://cloud.githubusercontent.com/assets/8103374/11110224/3e2c6508-88c7-11e5-84b9-26d4fc6dc8ab.png">

**Comment by andrewconnell** [comment]
Do you have `tsd` installed globally?

**Comment by LanceEa** [comment]
Yeah I have installed globally. As you can see I'm running version 0.6.5

<img width="575" alt="screen shot 2015-11-12 at 7 36 36 am" src="https://cloud.githubusercontent.com/assets/8103374/11118487/3301c940-8910-11e5-880d-fcb4f3c3efa0.png">

I also checked to make sure the folder and file existed. It does and you an see that I have user Read/Write permissions. I was able to open the file in Visual Studio Code too.

<img width="573" alt="screen shot 2015-11-12 at 7 49 13 am" src="https://cloud.githubusercontent.com/assets/8103374/11118699/e6df7d3a-8911-11e5-8b36-c2b8dfeffc08.png">

Could it be that it is trying to run the processes as "node" or "npm" and not as me?

**Comment by LanceEa** [comment]
Some other things that I have tried but no success:
1. Changed permissions on file to 777 which is full access to anyone (not ideal but just wanted it to work)
2. Changed ownership to "lance" and set group to "admin" per this Yo issue on Github https://github.com/yeoman/yeoman/issues/1097
3. Delete file from directory
4. Tried the famous windows restart on a Mac

None of these seemed to work...not sure what else to try at this point. Any thoughts?

**Comment by andrewconnell** [comment]
Have you tried to run TSD reinstall on it's own? Try this... uninstall the office generator if you haven't already installed it (verify it's not listed when you run `npm list -g --depth=0`). Then try cloning the repo locally straight from github, then run the tsd reinstall from the root (you can find the command [in this line on the package.json](https://github.com/OfficeDev/generator-office/blob/master/package.json#L27)). I suspect that there's an issue running this when the repo gets added.

Then, try to install it locally by running `npm link` within the cloned repo. This basically installs the locally cloned NPM module without downloading it from NPM's registry. You can always undo this by running `npm unlink`... this is how we do local development & testing of the generator.

Another option is to try installing an older version of the generator... I think the syntax is something like `npm install -g generator-office@0.5.0`

I've seen few issues since pushing 0.5.1 which updated this install step & I am planning to remove it to make it an optional step instead of an automatic one in the next update I do... that update is going to focus on the getting started experience (see #92).

**Comment by LanceEa** [comment]
I was able to install the 0.5.0 version and it worked like a charm. Let me know if you would like I can try the other approach as well to see if that would fix it too?

*Side Note* - I'm new to Open Source but would like to start getting more involved so let me know if there is anything specific you might like help on.

**Comment by andrewconnell** [comment]
OK... then that's a bug in automatically running **tsd** on install... that will get removed in the cleanup... thanks for working with me on this.

As for getting involved, best way to do it is to check the repo's issue list and look for the **[help-wanted](https://github.com/OfficeDev/generator-office/labels/help-wanted)** tag. Those are items we want in the generator but have no one working on them. Jump on the issue, converse, claim it and let us know you're working on it and we'll switch it from *help-wanted* to *in-process*

**Comment by andrewconnell** [comment]
Fixed in 57fd8c721d16a11c4ee8f7ceaa3c730753bb1baf
