### ISSUE TITLE
npm test not working on Windows

### ISSUE THREAD

**Issue by jthake** [OfficeDev/generator-office#115]
I believe the npm test has not been validated on Windows machines in command prompt. When I clone the master repo and run

``npm test``

I get the following error

``c:\git\generator-office>npm test``
``> generator-office@0.3.1 test c:\git\generator-office``
``> ./node_modules/mocha/bin/_mocha -R dot test/**``
``'.' is not recognized as an internal or external command,``
``operable program or batch file.``
``npm ERR! Test failed.  See above for more details.``

**Comment by andrewconnell** [comment]
Please update the generator and rerun... v0.3.1 is VERY old... current version is 0.6.1. Please update & feel free to reopen if you still have issue.

**Comment by jthake** [comment]
Yeah my bad, I was reviewing someones fork and didn't realize how behind the comits it was. Regardless, even with latest master I still get this error. "gulp test" runs fine though which is interesting.

**Comment by andrewconnell** [comment]
The two are different… the skinny: don’t know how to fix the NPM option, but the GULP option works xplat.

(1) The NPM one is using the command line tool and calls it using the path tot he file. The problem is that paths work differently on OS X & Windows. NPM TEST is just an alias to run the command you see in the package.json file. You can run that manually if you like. It works in OSX, but doesn’t work on Windows. Personally I want to leave it as is (a) as this is the generally accepted way to do it & (b) the primary audience for this tool are those not on Windows / Visual Studio; changing this goes against the primary audience IMHO.

(2) The GULP one does stuff internally to make sure it works on either Windows / OS X. So we have a cross browser option… use gulp to test if you want to use OS X / Windows… or use NPM for OS X.

Nothing wrong here & nothing but one less option for Windows developers to use to test, but they have an alternate.

AFAIK, leave it as is.

**Comment by waldekmastykarz** [comment]
I noticed that gulp test doesn't correctly report coverage: it always shows 100% while npm shows the same coverage as Travis when submitting PRs.

**Comment by andrewconnell** [comment]
Known bug in the reporter… ignore the report in the console. The report generated as mentioned in our dev docs is accurate and is what coveralls uses for coverage reporting.

**Comment by jthake** [comment]
yeah my report just says 100% too in the html :-1: 
the table in the html has zero rows.

**Comment by waldekmastykarz** [comment]
@jthake have you tried running `npm run-script test-travis`? On OS X it shows correct coverage.

**Comment by jasonjoh** [comment]
Here's an empty coverage report from `gulp test` on Windows if it helps (renamed to .txt since GitHub won't let you attach HTML)

[index.txt](https://github.com/OfficeDev/generator-office/files/67036/index.txt)

**Comment by jasonjoh** [comment]
@waldekmastykarz I tried running that on Windows and it failed with the same error Jeremy reported for `npm test`. I hacked a Windows-compatible version of the `test-travis` script:

    "test-travis-win": "node .\\node_modules\\istanbul\\lib\\cli.js 
      cover .\\node_modules\\mocha\\bin\\_mocha -- -v -R spec -t 100000 
      .\\test .\\test\\commands .\\test\\content .\\test\\mail .\\test\\taskpane"

And that made it work, though it's not every elegant. I guess the problem is the `/` vs the `\`, and how there's no equivalent of `**` wildcard in the Windows command prompt.

**Comment by andrewconnell** [comment]
** isn’t an OS thing, it’s a glob pattern

**Comment by jasonjoh** [comment]
It doesn't work though in the command prompt. If I leave it like that, it fails with "can't find module test"

**Comment by jthake** [comment]
how did you get your reporitng working per your comment in other thread?

**Comment by jasonjoh** [comment]
The hacked script entry in package.json :)

**Comment by jthake** [comment]
ok so you've changed this in you your forked build? can we get a pull request in to main for this change if so in master as a separate thing to resolve this particular issue?

**Comment by jasonjoh** [comment]
Yeah I changed it locally. It feels kind of hacky and I'm not sure if it's the "right" way to fix it. I'm happy to submit a PR if the hack is "good enough" though :).

**Comment by andrewconnell** [comment]
Those are used by travis. & coveralls for CI. If they break travis and coveralls they can't be accepted. Submission of a PR will trigger both to run. Don't break the build! :)

-AC
Sent from my mobile. Please excuse brevity and typos.




On Fri, Dec 18, 2015 at 5:14 PM -0800, "Jason Johnston" <notifications@github.com<mailto:notifications@github.com>> wrote:


Yeah I changed it locally. It feels kind of hacky and I'm not sure if it's the "right" way to fix it. I'm happy to submit a PR if the hack is "good enough" though :).

-

**Comment by andrewconnell** [comment]
I have added the project to [AppVeyor for automated testing on Windows](https://ci.appveyor.com/project/andrewconnell/generator-office) as PR #117. It is tested using a [matrix of the latest Node.js LTS version (4.2.3) & platforms (x86 & x64)](https://ci.appveyor.com/project/andrewconnell/generator-office/build/1.0.5). See a specific build & test result [here Node 5.2.0 on x86 here](https://ci.appveyor.com/project/andrewconnell/generator-office/build/1.0.5/job/mkce0c8uutfgyh2p).

@jthake this proves that the tests do run on Windows & provides a history showing it as well as the command to run :smile:

@jasonjoh the [script above you use to run the tests is overly complex](https://github.com/OfficeDev/generator-office/issues/115#issuecomment-165885736)... the `**` pattern does work on Windows... check the script that is run in the new build file `appveyor.yml` file. It's mostly the same, [it just calls Mocha using a slightly alternate path](https://github.com/OfficeDev/generator-office/blob/master/appveyor.yml#L24) to deal with changes between NPM on Windows & OSX / Linux.

**Comment by jasonjoh** [comment]
Awesome, thanks Andrew! I think my problem was due to leaving off the trailing '/*.js'.


Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by jthake** [comment]
OK so as per https://github.com/OfficeDev/generator-office/blob/master/docs/developer-testing.md we should just use "gulp test". as "npm test" does not work still.
When I look at HTML report..it still gives me no rows in that report and everything is 100%.

**Comment by andrewconnell** [comment]
@jthake let's level set...

`npm test` is simply a batch command / script that calls another command. As I said above, in `package.json` (*where it's defined*) it is using the syntax to run mocha & all the tests that work on a unix based box. As @jasonjoh & you have seen, it doesn't work on Windows. But you can see the command that does make it work on windows by looking at what's run in the [appveyor.yml file](https://github.com/OfficeDev/generator-office/blob/master/appveyor.yml#L24).

To get the code coverage report generated, while the `test` [gulp task does call istanbul](https://github.com/OfficeDev/generator-office/blob/master/gulpfile.js#L48-L60) to generate the coverage report, it has long standing known bugs (not us, it's them) and they are still in flux... sometimes they work, sometimes they don't. In my experience, when I need a trustworthy coverage report, I always manually run instanbul outside of gulp as the gulp tasks do not generate trustworthy reports 100% of the time.

If you really want to see the same report locally that is generated by Travis & sent to Coveralls that produces the badge [![Coverage Status](https://coveralls.io/repos/OfficeDev/generator-office/badge.svg?branch=master&service=github)](https://coveralls.io/github/OfficeDev/generator-office?branch=master) we have on the homepage and the official results, look at the script **test-travis** in the `package.json` file [here](https://github.com/OfficeDev/generator-office/blob/master/package.json#L30) and run it manually on your Windows box (*keep in mind, the script is written to work on unix just like `npm test` so you'll need to tweak it a bit for your Windows machine*).

Now, with all this being said, the current primary audience of the generator is for OSX / Linux developers. Running & testing on Windows is entirely possible, but considered a cute little toy for now... because if you're on Windows, you have Visual Studio & the templates provided there. As such all the test runs & coverage runs are written to work on Unix... can't write them for cross platform because the command line is different on Windows & Unix. If someone wants to write ADDITIONAL scripts for Windows and submit a PR, by all means go for it, but the scripts we have need to be left as is.

**Comment by jthake** [comment]
I wouldn't necessarily assume that this generator is targeting just OSX/Linux. It is intended for all. The reason being is that the generator will have things in it that will take longer to get into the Visual Studio 2015 tooling or in some cases won't make it. Between you, me, @waldekmastykarz and @jasonjoh there has already been value in things that can't be done in Visual Studio on Windows.

At any rate. I had a look at the package.json file and this line
`"./node_modules/istanbul/lib/cli.js cover ./node_modules/mocha/bin/_mocha -- -R spec -t 100000 test/**"`
How would I execute this from Windows Command Prompt?


I can run
```
node_modules\.bin\_mocha -R dot "test\**\*.js"
c:\git\generator-office>node_modules\.bin\_mocha -R dot "test\**\*.js"


  ......................................................................................................................................................................................
  ......................................................................................................................................................................................
  ......................................................................................................................................................................................
  ........................................

  586 passing (51s)
```
but no report is outputted by mocha it seems.


I installed instanbul
`npm install -g istanbul`

I tried
```
c:\git\generator-office>istanbul cover "test\**\*.js"
Unable to resolve file [test\**\*.js]
Try "istanbul help" for usage
```

And then tried to run one of the tests:
```
istanbul cover ".\test\content\existingproj-html.js"

No coverage information was collected, exit without writing coverage information
c:\git\generator-office\test\content\existingproj-html.js:24
describe('office:content', function () {
^

ReferenceError: describe is not defined
    at Object.<anonymous> (c:\git\generator-office\test\content\existingproj-html.js:24:1)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Object.Module._extensions.(anonymous function) [as .js] (C:\Users\jthake\AppData\Roaming\npm\node_modules\istanbul\lib\hook.js:109:37)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Function.Module.runMain (module.js:457:10)
    at runFn (C:\Users\jthake\AppData\Roaming\npm\node_modules\istanbul\lib\command\common\run-with-cover.js:122:16)
    at C:\Users\jthake\AppData\Roaming\npm\node_modules\istanbul\lib\command\common\run-with-cover.js:251:17
    at C:\Users\jthake\AppData\Roaming\npm\node_modules\istanbul\lib\util\file-matcher.js:68:16
```

can you help a brother out? ;-)

**Comment by andrewconnell** [comment]
To the point about Windows, I’m not saying that this isn’t going to work on Windows… all I’m saying is the *developer experience* for customizing / working ON the generator (not running it on Windows) is not a use case that was factored in dev.

First, istanbul does not need to be installed the way you did it… [it’s already installed](https://github.com/OfficeDev/generator-office/blob/master/package.json#L73) as a `devDependency`.

Second, istanbul does not run tests so your call to istanbul isn’t valid. Istanbul tells mocha to run the tests & then istanbul watches the code tested to see what’s covered by the tests.

Using the same process I mentioned above that I setup for running tests, poking around I got it to build the tests and write the coverage report to the `/coverage` folder… assuming you are in the root of the generator…

```
node_modules\.bin\istanbul cover --hook-run-in-context node_modules\mocha\bin\_mocha -- -R min "test\**\*.js"
```

If you want to see the tests get run, change the reporter from "min" to something like "dot" or "spec".

FWIW, I've seen TONS of people have issues with istanbul on Windows because of how the Windows command line works. You could always run it using the gitbash command prompt you have with git.

**Comment by andrewconnell** [comment]
To the point about Windows, I’m not saying that this isn’t going to work on Windows… all I’m saying is the *developer experience* for customizing / working ON the generator (not running it on Windows) is not a use case that was factored in dev.

First, istanbul does not need to be installed the way you did it… [it’s already installed](https://github.com/OfficeDev/generator-office/blob/master/package.json#L73) as a `devDependency`. 

Second, istanbul does not run tests so your call to istanbul isn’t valid. Istanbul tells mocha to run the tests & then istanbul watches the code tested to see what’s covered by the tests.

Using the same process I mentioned above that I setup for running tests, poking around I got it to build the tests and write the coverage report to the `/coverage` folder… assuming you are in the root of the generator…

```
node_modules\.bin\istanbul cover --hook-run-in-context node_modules\mocha\bin\_mocha -- -R min "test\**\*.js"
```

If you want to see the tests get run, change the reporter from "min" to something like "dot" or "spec".

FWIW, I've seen TONS of people have issues with istanbul on Windows because of how the Windows command line works. You could always run it using the gitbash command prompt you have with git.

**Comment by ksawalme** [comment]
when I put npm test I got this message,,,,,, please help 

at Object.<anonymous>.test (test/functions.test.js:69:30)
          at new Promise (<anonymous>)
          at <anonymous>

Test Suites: 1 failed, 1 total
Tests:       4 failed, 4 skipped, 8 total
Snapshots:   0 total
Time:        12.969s
Ran all test suites.
npm ERR! Test failed.  See above for more details.

**Comment by ksawalme** [comment]
I use windows 10 to test
I hade Linux before it's fully working but the Linux not available right now

please help

**Comment by umbravi** [comment]
If adding bat scripts is worth the effort to make windows development easier, then the scripty library would be useful: [scripty - github](https://github.com/testdouble/scripty), [scripty - npm](https://www.npmjs.com/package/scripty)

Scripty is a script management tool that hooks into the "npm run" command and allows flexibility in writing specific scripts without the limitations and clutter of the json file. Platform specific scripts can also be written, and will be selected automatically by scripty on execution of a "npm run" command.

Below is an example of what the project I'm currently working on looks like with this implemented:
```
+---node_modules
+---scripts
|   +---unix
|   |   |   build.sh
|   |   |   coverage.sh
|   |   |
|   |   \---test
|   |           index.sh
|   |           int.sh
|   |           server.sh
|   |           unit.sh
|   |
|   \---win
|       |   build.bat
|       |   coverage.bat
|       |
|       \---test
|               index.bat
|               int.bat
|               server.bat
|               unit.bat
|
+---src
\---test
```
package.json:
```
"scripty": {
    "path": "./scripts/unix",
    "windowsPath": "./scripts/win"
  },
"scripts": {
    "test": "scripty",
    "test:server": "scripty",
    "test:unit": "scripty",
    "test:int": "scripty",
    "test:snap": "CHAI_JEST_SNAPSHOT_UPDATE_ALL=true npm run test:unit",
    "start": "node ./src/server-entry.js",
    "build": "scripty",
    "lint:js": "eslint src scripts test --ext .js",
    "lint:styles": "sass-lint --verbose -c .sass-lint.yml",
    "coverage": "scripty",
    "coverage:check": "babel-istanbul check-coverage"
  }
```
