### ISSUE TITLE
damaged icons

### ISSUE THREAD

**Issue by Hongbo-Miao** [OfficeDev/generator-office#248]
When I do these steps below, it generates a assets folder with four damaged icons.

<img width="490" alt="yo-office" src="https://user-images.githubusercontent.com/3375461/27891924-7d1ef31a-61b1-11e7-96c9-6050a94f1f5e.png">

<img width="490" alt="icons" src="https://user-images.githubusercontent.com/3375461/27891915-72cf92d4-61b1-11e7-8252-1da0d36c333c.png">

**Comment by TCourtneyOwen** [comment]
@Hongbo-Miao This is quite an old issue, and we haven't heard of any similar issues in the numerous yo office updates we have published since this issue was originally opened. Please update to the latest version of yo office (1.3.0) to see if this fixes the issue. If not, please reopen the issue and we will investigate further.

Thanks,

Courtney
