### ISSUE TITLE
Installing add-in fails on Outlook for Mac

### ISSUE THREAD

**Issue by dylanjt** [OfficeDev/generator-office#265]
**Context**
I am on macOS High Sierra and using Outlook for Mac 15.40 (171108) licensed as a Office 365 Subscription. I have followed the directions to generate a boilerplate from the README, including adding browser-sync's certificate to my keychain. I have tried the scaffolds for jQuery, Angular, and am presently using React. I can `npm run start` and spin up fine, and in my browser I see the "Please sideload your addin to see app body" message.

**Problem**
However, when I go to Outlook -> Store -> add custom add-in -> and open my manifest file, I get a message saying the installation is taking longer than expected, followed by a message that says the installation failed.

**Questions**
Is there a way to check out Outlook's reasoning behind this installation failure? Is development on Mac no longer supported?

**Also**
`npm run validate engage-for-outlook-manifest.xml` fails:

```
validate-office-addin "engage-for-outlook-manifest.xml"

env: node\r: No such file or directory
```

I can confirm that that manifest file is definitely there.

**Comment by beth-panx** [comment]
@dylanjt go to [Manage add-ins](https://outlook.office.com/owa/?path=/options/manageapps) page to add your manifest file and make sure you turn it on afterwards.

As for the error you got when running `npm run validate your_file.xml`, the `\r` means you have a carriage return in the shebang line, likely due to Windows-style line endings.
