### ISSUE TITLE
Cannot install self-signed cert using Windows guide

### ISSUE THREAD

**Issue by jogule** [OfficeDev/generator-office#292]
In the [Windows guide to install self-signed cert](https://github.com/OfficeDev/generator-office/blob/master/src/docs/ssl.md
) the first step says "Go to {project root}\certs"

However such path doesn't exist in my generated project.

![office add in screenshot](https://user-images.githubusercontent.com/1463886/37934126-dc0e6de8-3112-11e8-8bb4-471343ff3fd0.PNG)

This is a project generated with yo and react

https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/excel-quickstart-react

**Comment by eode** [comment]
Same issue.  No 'certs' directory.

**Comment by eode** [comment]
This is an issue with how react projects are generated -- specifically, they don't allow custom SSL certs to be used without some monkeying about, and it looks like the idea of SSL was just abandoned instead of the docs being updated or problem being fixed.   To resolve:

* create a non-react app with yeoman, and move the 'certs' folder to your react project's folder
* Install [react-app-rewired](https://github.com/timarney/react-app-rewired) into your project, modifying `package.json` accordingly
* use the example for modifying the `devServer` config
  * **do not** set the `ca` or `passphrase` options.
  * Either use the environment variables they chose to specify the `key` and `cert` paths, or just read in the correct files directly from the `certs` dir.

**Comment by akrantz** [comment]
@eode Please provide the specific answers to the Yo Office prompts.

When I do this, I get a certs directory that works with webpack-dev-server. 

Answers to the prompts:
? Would you like to create a new subfolder for your project? Yes
? What do you want to name your add-in? React Excel Add-in
? Which Office client application would you like to support? Excel
? Would you like to create a new add-in? Yes, I need to create a new web app and manifest file for my add-in.
? Would you like to use TypeScript? Yes
? Choose a framework: React

**Comment by TCourtneyOwen** [comment]
@jogule We now generate the certificates via office-addin-dev-certs and automatically register them during "npm run build". Closing this issue as resolved
