### ISSUE TITLE
Add Vue template generator

### ISSUE THREAD

**Issue by cakriwut** [OfficeDev/generator-office#358]
Vue template is not available in current version.

**Comment by fuzzzerd** [comment]
That'd be a very useful template, since its very light weight compared with something like Angular, but the jQuery template leaves a little something to be desired.

**Comment by Chris2011** [comment]
I still would like to see the support of Vue from you @cakriwut in this repo here :)

**Comment by Shujee** [comment]
Any update on this one? Strange that both Angular and React are supported, but Vue is not.

I went ahead and tried to do it manually. Started with `yo office` in the current folder, followed by `vue create .` to merge both installations in a single repo. This fails because these two packages target conflicting versions of `Typescript` package. 

My goal is to somehow keep debugging capabilities of the yeoman project, but remove all content from it and instead launch Vue project's `serve` script and update the yeoman manifest to connect to it. The problem however is that yeoman project launches its own webpack/web server instance even when the manifest is pointing to my Vue project's server. I think this has something to do with the webpack configuration (`webpack.config.js`) but I haven't been able to fix it yet. Node is not my strongest area.

So ideally what I want to do is this:

1. Create a Vue CLI project.
2. Merge `yo office` generated output into the Vue project, hopefully without any dependency conflicts.
3. Remove all content from `yo office` including taskpanes and commands, but leave the debug configurations in there.
4. Update manifest file to point to my Vue project's server.
5. Create a compound configuration in `launch.json` that fires up `npm run serve` on the Vue project and `npm run start` on yeoman project so that it starts debugging against my Vue dev server. Plus somehow stop yeoman configuration to fire up webpack to create its own instance of http server.

**Comment by millerds** [comment]
We track feature requests on our [Tech Community Page](http://aka.ms/M365dev-suggestions). Please submit your request there and choose the appropriate label(s). Feature requests on Tech Community are considered, when we go through our planning process.
