### ISSUE TITLE
optimize test execution performance

### ISSUE THREAD

**Issue by ThorstenHans** [OfficeDev/generator-office#375]
Executing all unit tests takes a couple of minutes due to heavy file io and network traffic. Maybe there is a way the test execution performance can be optimized.

**Comment by akrantz** [comment]
I would like to see each of the templates moved out to separate git repositories (with one master repository linking to each as a submodule providing a way to browse all of the templates) so that each repository can have tests to validate that the template works. We can use "office-addin-manifest modify manifest.xml [options]" to be able to modify the manifest when the template is cloned as the basis of a new add-in. This would allow each template to have their own tests which can be run and would make it easier to make pull requests and validate each template independently without having to run Yo Office to clone it.

This would remove the need to have generator-office tests of the templates themselves.

**Comment by ThorstenHans** [comment]
good point @akrantz, but do you think maintaining those repositories is worth it. They'll be outdated almost every 2nd week due to SPA FX updates...

Wouldn't it make more sense to remove almost all the templates from the repos and instead of maintaining the templates on our own, we could automate the SPA frameworks CLIs like `@angular/cli` for NG or `create-react-app` for React.... 

As I've already requested in #365

**Comment by akrantz** [comment]
Yes, where possible we should do that.

**Comment by ThorstenHans** [comment]
How could that be achieved? Can you guys create a dedicated branch where I could sent PRs to? Or should PRs in that direction directly go to `master`? 

Having this change in mind, a quick OT question: what is the release cycle for `generator-office`?

**Comment by akrantz** [comment]
It would likely be PRs against master. 

We don't have a set cadence for generator-office, and will make a release once we have a set of changes that are sufficient to be released.

**Comment by ThorstenHans** [comment]
cool, so I'll close this issue because it'll become obsolete no matter which direction the generator evolves.
