### ISSUE TITLE
What are app.css, root webpack.config.js and resource.html for when generating React Outlook add-in

### ISSUE THREAD

**Issue by tombell** [OfficeDev/generator-office#428]
I am playing around looking into Outlook add-ins to determine if it's viable to create one for our company.

I've generated an Outlook add-in with the React template (with TypeScript implied), and I am wondering what the following files are for, which look like a mix up when copying files from base and react templates:

- `resource.html` (from `react` template)
- `app.css` (from `base` template)
- `webpack.config.js` (from `base` template, even tho `react` template has webpack configs in `config/`)

From what I've been playing with, these files are safe to delete for a `react` based add-in. But also makes we wonder what other superfluous files are generated.

**Comment by TCourtneyOwen** [comment]
Hi Tom,

Your comment about superfluous files is indeed valid, and something we have been discussing this internally.  In fact, we are making attempts to greatly simplify the existing React project template so that it doesn't deviate so much from React projects created via **create-react-app**.

Regarding the specific files you mention:
- resource.html - purely informational and can be removed (this will be removed in future versions)
- app.css - really shouldn't be in the template at all since it's not used anywhere.
- webpack.config.js - actually not needed to build the project. This surprised me, but I just removed it locally and was able to successfully build a working project.

Please stay tuned for upcoming changes to the project templates which should simplify things and hopefully lead to less confusion.

Thanks,

Courtney

**Comment by tombell** [comment]
@TCourtneyOwen awesome, thanks for the quick response. I noticed the React template can be quite overwhelming when first looking at it.

Thanks for confirming those files aren't needed, I did grep the code base to check if they're referenced anywhere. 👍🏻
