### ISSUE TITLE
Disparity between office-generator and VS templates

### ISSUE THREAD

**Issue by shweaver-MSFT** [OfficeDev/generator-office#458]
generator-office is awesome! Works well and has great room for growth.

That said, the output for generator-office is *dramatically* different than the Visual Studio templates for Office Add-Ins.

Why the divergence? Which is the "preferred" path for setup? Is your team continuing to invest in the VS templates?

Just want to make sure I'm not missing anything :)

**Comment by kbrandl** [comment]
@shweaver-MSFT thanks for the feedback! Although we're continuing to invest in the Visual Studio templates, it's been some time since they were last updated. At least until that happens, I'd personally recommend that you use **generator-office** to create add-in projects, if doing so is feasible for you. Not only does **generator-office** provide more options (e.g., it supports creating projects using Angular or React, where as Visual Studio does not), the project templates in **generator-office** also demonstrate current best practices for project structure, coding patterns, etc. We hope to update the VS templates again before too much longer (exact timeframe still TBD), and will announce broadly (on the Office Developer blog, etc.) when that happens. 

Hope this helps answer your question. I'm going to go ahead and close this issue now, but please feel free to comment further here if you'd like additional clarification about anything.

**Comment by akrantz** [comment]
Also, with the release of VS 2019, I believe the open folder functionality should allow using the projects created from generator office with Visual Studio in much the same way as VS Code. If you want to try this out, it would be great to get feedback. I've been meaning to try this but haven't had the opportunity to explore it in detail.
