### ISSUE TITLE
support importing scss files to add-ins

### ISSUE THREAD

**Issue by asith-w** [OfficeDev/generator-office#460]
support importing scss files to add-ins.

**Comment by akrantz** [comment]
You should be able to take an existing project and add Sass to it. It would be great if you could provide an example of doing this. 

Get the basic taskpane template at https://github.com/OfficeDev/Office-Addin-Taskpane, create a topic branch (e.g. "sass"), make changes, push it to your fork. That will show the changes necessary for Sass support.

**Comment by AhmadiRamin** [comment]
I'm trying to use SCSS files in my solution but seems it's not working as I expected.
I configured webpack, and I can see .d.ts file next to each scss file but at runtime, I get undefined error.

**Comment by igor-ribeiiro** [comment]
It should be doable but you probably need to make changes to webpack. I don't think this is an issue with our templates and is more of a question to be asked in [StackOverflow](https://stackoverflow.com/).
I will be then closing the issue. Feel free to reopen if you find SCSS is not working because of some bug/problem in the template.
