### ISSUE TITLE
The entire Office-Addin-Scripts repo is missing

### ISSUE THREAD

**Issue by jasonqsong** [OfficeDev/generator-office#466]
The office generators are using Office-Addin-Scripts a lot and all links to this repo is deprecated. If it's a refactor, where should we submit issues.

My specific issue is that office-addin-dev-certs only support win and darwin, it doesn't support WSL

in office-add-in-dev-certs/lib/verify.js

```
    switch (process.platform) {
        case "win32":
            return `powershell -command "dir cert:\\CurrentUser\\Root | Where-Object Issuer -like '*CN=${defaults.certificateName}*' | Where-Object { $_.NotAfter -gt [datetime]::today } | Format-List"`;
        case "darwin": // macOS
            return `security find-certificate -c "${defaults.certificateName}" -p | openssl x509 -checkend 86400 -noout`;
        default:
            throw new Error(`Platform not supported: ${process.platform}`);
```

**Comment by akrantz** [comment]
The https://github.com/OfficeDev/Office-Addin-Scripts is now public. You can create an issue there.

Since Office doesn't run on Linux, we did not include support. I'm not sure whether the same commands as MacOS work on WSL or if it would need another command to install/remove/verify the certificate.

If you are able to find out what works and want to make a pull request, you could be the first public submission!
