### ISSUE TITLE
Is it possible to use native node modules within an Excel add-in ?

### ISSUE THREAD

**Issue by pasdechancee** [OfficeDev/generator-office#478]
Hello everyone, I'm new to Office add-ins. I wish to leverage a cpp library within an Excel add-in

**Here's what I did so far** :
 
`yo office --projectType excel-functions --name GiacAddin --host excel --js`

and basically here's **what I wish I could do** in src/functions/function.js :

```${js}
var giac = require("bindings")("giac");

/**
 * Does awesome computation
 * @customfunction
 * @param {string} to_evaluate Expression that will be evaluated by giac
 * @returns {string} Giac's output
 */
function evaluate(to_evaluate) {
  return giac.evaluate(to_evaluate);
}
```

But then obviously I'm getting errors because I can't run a native module in the browser...

Is this doable and if so, how ? Do I need to use an Express server to make the computation and then an ajax request on the frontend ?

P.S : I'm running the server add-in on Linux and I use the web version to load the add-in which works fine with the default functions (ADD; CLOCK, ...)

**Thank you** for your time, any help is very much appreciated !

**Comment by kbrandl** [comment]
@pasdechancee thanks for your interest in Office Add-ins development! Issues in this repo are intended to report problems with (or submit feature requests for) the Yeoman generator for Office Add-ins. Programming how-to questions like this are better suited for Stack Overflow, where you'll reach a broader audience of folks with expertise in the area, and others can benefit from the feedback you receive there. I'm going to close this issue here, but can you please post your question to Stack Overflow (tagged with [office-js](https://stackoverflow.com/questions/tagged/office-js) and [custom-functions-excel](https://stackoverflow.com/questions/tagged/custom-functions-excel)) instead? Thanks!
