### ISSUE TITLE
Unable to install the CA certificate

### ISSUE THREAD

**Issue by MohamedMusthaque** [OfficeDev/generator-office#482]
Tried to run **npm run dev-server**
But gave this issue.

![image](https://user-images.githubusercontent.com/9990475/63588619-98d70100-c5c4-11e9-89ca-72c21f00a4cc.png)

Have tried by re-installing. Still give the same issue.
Update the everything.

**Comment by akrantz** [comment]
I believe that you haven't actually updated the package. You can see the current package version being used using `npm ls office-addin-dev-certs` and the latest version using `npm dist-tag ls office-addin-dev-certs`.

To ensure that you get the latest package, try this:
npm uninstall office-addin-dev-certs
npm install -D office-addin-dev-certs

After this, you should have the latest version which has the fix for spaces in the file path, and `npm run dev-server` should then work. Before running that you can also run `npx office-addin-dev-certs install` to ensure the dev certs are installed.

Let me know whether this helps fix things for you.

**Comment by MohamedMusthaque** [comment]
Thanks @akrantz 
It worked.
I tried in additional to that, `npm instal -D office-addin-dev-certs`
