### ISSUE TITLE
Error: connect ETIMEDOUT 140.82.118.4:443

### ISSUE THREAD

**Issue by nosaku** [OfficeDev/generator-office#498]
Running "yo office" behind corporate proxy. Getting following error. NPM proxy settings didn't help.

AppData\Roaming\npm\node_modules\generator-office\node_modules\cls-hooked\context.js:177
      throw exception;
      ^

Error: connect ETIMEDOUT 140.82.118.4:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1104:14)

**Comment by stecy** [comment]
Got the same error.

**Comment by TCourtneyOwen** [comment]
Sorry to hear you are having problems. Could you please run the following and say yes when presented with a dialog asking to install certificates: ‘npx office-dev-certs install’. Sometimes this dialog gets hidden behind other windows when running ‘npm start’. After installing the certificates please try running npm start again.  Let me know if that fixes things for you. If not, please provide details for the project type (e.g. Angular, React) and the OS you are using. 

Thanks,

Courtney

**Comment by stecy** [comment]
Thanks for your help.

I installed the certs (npx office-addin-dev-certs install) but no positive effect command yo office :

`\node\node_modules\generator-office\node_modules\cls-hooked\context.js:177
      throw exception;
      ^

Error: connect ETIMEDOUT 140.82.114.3:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1128:14) {
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '140.82.114.3',
  port: 443,
  'error@context': { _ns_name: 'AI-CLS-Session', id: 312 }
}`

**Comment by stecy** [comment]
The problem come from Yeoman.  

`yo doctor` give me timeout errors.

**Comment by esominion** [comment]
getting same issue -
× yo version
ErrorClass [RequestError]: connect ETIMEDOUT 104.16.24.35:443
    at ClientRequest.<anonymous> (C:\Users\xxxxxx\AppData\Roaming\npm\node_modules\yo\node_modules\latest-version\node_modules\got\index.js:73:21)
    at Object.onceWrapper (events.js:313:26)
    at ClientRequest.emit (events.js:223:5)
    at ClientRequest.EventEmitter.emit (domain.js:475:20)
    at TLSSocket.socketErrorListener (_http_client.js:406:9)
    at TLSSocket.emit (events.js:223:5)
    at TLSSocket.EventEmitter.emit (domain.js:475:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:81:21) {
  code: 'ETIMEDOUT',
  message: 'connect ETIMEDOUT 104.16.24.35:443',
  host: 'registry.npmjs.org',
  hostname: 'registry.npmjs.org',
  method: 'GET',
  path: '/yo'
}

**Comment by TCourtneyOwen** [comment]
@esominion Is this error occurring when running 'npm start"? Did you configure your dev-server to run on port 443 (the default port for the yo office projects is 3000)?

**Comment by esominion** [comment]
I got this when I was running 'yo doctor' and 'yo office'

**Comment by TankDoor** [comment]
I'm getting the exact same problem. Is there a fix to this yet?

**Comment by TCourtneyOwen** [comment]
@TankDoor @esominion I suspect the problem is not with Yo Office but rather with accessing the project template repo that Yo Office uses to create a project.  For example, if you are attempting to creating a typescript Office Add-in Task Pane project, Yo Office pulls from this repo:  https://github.com/OfficeDev/Office-Addin-TaskPane.  Are you able to access this repo?  If not, then Yo Office won't be able to either, and it likely means your proxy settings are blocking it.

Can you please check and see if you are able to access and clone https://github.com/OfficeDev/Office-Addin-TaskPane?

Thanks,

Courtney

**Comment by TankDoor** [comment]
Thanks for the response.
I am able to access those things but I got round the issue a few moments ago.
Turns out I had to create environment variables and set them all to my proxy address:

GLOBAL_AGENT_HTTP_PROXY
HTTP_PROXY
HTTPS_PROXY

I think it is because the global-agent library used by Yeoman draws all its varues from the environment valiables.

**Comment by TCourtneyOwen** [comment]
Closing this issue, as it's quite old and we haven't heard additional feedback on this issue. Please reactivate if this is still an issue

**Comment by fredigj** [comment]
I'm getting the same error but only after I connect to my corporate vpn
