### ISSUE TITLE
cannot edit registry

### ISSUE THREAD

**Issue by tsraza** [OfficeDev/generator-office#512]
Please remove the requirement to edit the registry.  Can we use environment variables instead?

```
ERROR: Registry editing has been disabled by your administrator.
```

**Comment by aagamdoshi** [comment]
Also facing the same issue.. Is there a solution found for this issue

**Comment by TCourtneyOwen** [comment]
@tsraza @aagamdoshi Can you please be more specific about the scenario where you are required to edit the registry?  Generator-office itself doesn't require any registry edits, so are you referring to a project derived from generator-office?  Please provide steps so I can reproduce this behavior.

Thanks,

Courtney

**Comment by tsraza** [comment]
If you remove any existing Micosoft Developer entries from the registry, disable registry editing, then try to `npm install` you should get the error.  It is specific to microsoft projects, not only the generator-office package.  This issue can be moved to the project that is requesting write-access to the registry, if it can be identified.

I could not trace it back but it most likely has something to do with this: https://github.com/OfficeDev/Office-Addin-Scripts/blob/master/packages/office-addin-dev-settings/src/dev-settings-windows.ts

**Comment by TCourtneyOwen** [comment]
@tsraza Just to clarify, is this the error your see:
Debugging is being started...
App type: desktop
Error: Unable to start debugging.
Error: Unable to set registry value "UseDirectDebugger" to "1" (REG_DWORD) for key "HKCU\SOFTWARE\Microsoft\Office\16.0\Wef\Developer\704cb52f-ba5e-45c2-b104-8cc7460ca61a".
ProcessUncleanExitError: ADD command exited with code 1:
ERROR: Registry editing has been disabled by your administrator.

This issue is presumably caused by https://github.com/TCourtneyOwen/Office-Addin-Scripts/blob/master/packages/office-addin-dev-settings/src/dev-settings.ts.  

I see that there is a '--no-debug' for Office-Addin-Debugging which should in theory bypass the need to write debug settings to the registry but it's doesn't appear to be working for me.

Adding @akrantz who may have more insight here

**Comment by tsraza** [comment]
@TCourtneyOwen Yes.

```bash
npm install -g yo generator-office
yo office --projectType taskpane --host excel --name exceladdin --ts true
cd exceladdin
npm run start
```

and that error comes up

**Comment by TCourtneyOwen** [comment]
While I've figured out a way to disable writing the dev-settings values to the registry with a local change, it's not going to be easy to get everything working end-to-end because of the registerAddin step in https://github.com/OfficeDev/Office-Addin-Scripts/blob/master/packages/office-addin-dev-settings/src/sideload.ts.  Writing to registry is required when automatically sideloading an add-in

One way to work around things is to start your dev-server via "npm run dev-server" and then manually register your add-in via these steps: https://docs.microsoft.com/en-us/office/dev/add-ins/testing/create-a-network-shared-folder-catalog-for-task-pane-and-content-add-ins.

After you've manually registered your addin, just keep the dev-server running and then start your Office Application.

Not ideal obviously, but the ability to write to the registry is required to allow for automatic registration of the add-in

**Comment by aagamdoshi** [comment]
So in that case , it becomes mandatory to have admin access , if we don't what to do this steps manually.

Also , when i try to run `npm run dev-server` i dont get to see the hosted site, rather i see the file structure. I have already raised a concern with @TCourtneyOwen  

> [Link for Office-Addin-TaskPane-Angular which has issue](https://github.com/OfficeDev/TrainingContent/issues/699)

**Comment by TCourtneyOwen** [comment]
Yes, that's correct you need to have admin permissions in order to do the automatic registration of the add-in, as we write the location of the add-in manifest to Computer\**HKEY_LOCAL_MACHINE**\SOFTWARE\Microsoft\Office\16.0\WEF.

As for issues with the dev-server, I've provided guidance at https://github.com/OfficeDev/TrainingContent/issues/699

Thanks,

Courtney
