### ISSUE TITLE
quick start example is something wrong

### ISSUE THREAD

**Issue by zironycho** [OfficeDev/generator-office#520]
I just executed the command as  `yo office`. and I choose the options as ms-office, react, and javascript. And I think my result screen is something wrong.
I captured the my `https://localhost:3000`. 

What I have to do next?

```
node: v12.16.1
npm: 6.13.4
- yo@3.1.1
- generator-office@1.6.1
```

<img width="809" alt="Screen Shot 2020-03-16 at 7 32 07 PM" src="https://user-images.githubusercontent.com/849052/76748012-65a4cb00-67bd-11ea-8d97-b669f06024e8.png">

**Comment by TCourtneyOwen** [comment]
@zironycho Sorry to hear you are having  problems.  I am a bit unclear what your problem is. Which host did you select for your project (for example, Excel, Word, PowerPoint)? 

When you run "npm start" from the root of your project directory, the host you selected should launch and then you will see a button in the upper right-hand corner of the UI that says "Show Taskpane". Are you seeing this?

Thanks,

Courtney

**Comment by zironycho** [comment]
@TCourtneyOwen Thank you for quick response.  I selected powerpoint project, and I don’t have the office365 now. To test the add-ins app, should I have a office365? I thought I didn’t need the office365 through the link below.

![](https://github.com/OfficeDev/generator-office/blob/master/src/docs/assets/browsersync.gif)

**Comment by TCourtneyOwen** [comment]
@zironycho You can test the addin in **Office Online** by opening a PowerPoint presentation in [OneDrive,](https://products.office.com/en-us/onedrive/online-cloud-storage) selecting Insert --> Add-ins --> Manage My Add-ins --> Upload My Add-in and then uploading the manifest.xml in your project. Please note, you will need to run "npm start" in your project so that the dev-server is running (it appears you are already doing this).

-Courtney

**Comment by zironycho** [comment]
@TCourtneyOwen Thank you for answer. It works!

**Comment by TCourtneyOwen** [comment]
Great glad to hear it!
