### ISSUE TITLE
Hosting on Linux

### ISSUE THREAD

**Issue by bwong199** [OfficeDev/generator-office#522]
Hi, 

I am currently experiencing this problem. 

https://github.com/OfficeDev/generator-office/issues/490

How do I host this on Azure? Thanks.

**Comment by nokafor** [comment]
Hi @bwong199 just so I understand, are you looking for instructions to host your add-in on Azure?

**Comment by dubeg** [comment]
@nokafor I've been looking for a step-by-step guide somewhere on how to deploy a project based on the TaskPane template to an Azure App Service (Linux with nodeJS).

**Comment by dubeg** [comment]
@nokafor Nevermind, I just realized that we don't need a Node web server, just serving static files is enough. Weird that this isn't managed by Office on the web itself, but I guess Office Scripts will fill our needs on that side.

So I setup an Azure Staticwebsite plugged with github, and modified the webpack config a bit to copy in the "dist" folder a default index.html file (since the Azure side refuses a deployment if it doesn't contain a "index.html" file), and to copy the assets folder as well because it is referenced in the generated manifest.

**Comment by akrantz** [comment]
I noticed recently that for production builds, the assets are not provided. I'm going to make an update to the Yo Office templates with a fix for this.

If you modify the webpack.config.js so that the module for the assets has the following config, it will output the assets with their original path. 

```
        {
          test: /\.(png|jpg|jpeg|gif)$/,
          loader: "file-loader",
          options: {
            name: '[path][name].[ext]',
          }          
        }
```

In taskpane.ts, you can reference the assets in the manifest, so they will be included in the build output in the dist folder.

```
// images referenced in the manifest
import "../../assets/icon-16.png";
import "../../assets/icon-32.png";
import "../../assets/icon-80.png";
```

I hope this helps.

**Comment by dubeg** [comment]
@akrantz It seems a bit weird to put the import in the taskpane.ts, but that works. Thank you!

**Comment by akrantz** [comment]
Sure, if you know a different way to let webpack know to keep these assets it would be useful. This seemed to be the easiest way to do it that I could find.

**Comment by dubeg** [comment]
I've no idea to be honest. In my case, I added two plugins but I have honestly no idea what the good practices are, I rarely do web development.

For reference, I did it that way:
```
...
      new CopyWebpackPlugin([
        {
          to: "index.html",
          from: "./src/index.html"
        }
      ]),
      new CopyWebpackPlugin([
        {
          to: "assets",
          from: "./assets"
        }
      ]),
...
```

**Comment by millerds** [comment]
Sounds like this was solved.  If it wasn't, please reopen
