### ISSUE TITLE
Angular app lists the directory contents instead of the actual app

### ISSUE THREAD

**Issue by Ricalo** [OfficeDev/generator-office#54]
When browsing to the root of the app, I see the contents of the root folder.
![image](https://cloud.githubusercontent.com/assets/989368/10354456/c0420b52-6d14-11e5-9426-8eae454c69f0.png)

However, I think what you're trying to show is something like the following image
![image](https://cloud.githubusercontent.com/assets/989368/10354405/5dd6f39c-6d14-11e5-8d8c-b48bb81987ac.png)

If this is right, you just need to add *ng-app* and *ng-controller* directives to `index.html`

```html
<html ng-app="officeAddin">
...
<body id="container" ng-controller="homeController">
```
and set `directoryListing: false` in `gulpfile.js`

**Comment by andrewconnell** [comment]
Actually this won't work reliably. There's a conflict with `office.js` and angular where the clobber each other on load. Sometimes it works, but other times it doesn't so the safest way to get an angular app loaded is to manually bootstrap it as we do [here in a mail addin](https://github.com/OfficeDev/generator-office/blob/master/generators/mail/templates/ng/appread/app.module.js#L21).

In addition I'd recommend we not use `ng-controller` because it's deprecated in ng2 and conflicts with most of the accepted style guides.

Back to your question... which type of an addin did you create that was causing this issue?

**Comment by Ricalo** [comment]
I saw that behavior in task pane and mail apps.
It's good to see that you've figured a way to load the app. I'll do some more testing during the week.
