### ISSUE TITLE
Make localhost "safe"

### ISSUE THREAD

**Issue by martellaj** [OfficeDev/generator-office#70]
I'm unfamiliar with SSL certificates and the like, but is there anyway to make the server started by Gulp "safe"? Unless you go to the index.html page in a browser and accept that it's unsafe, the Add-in fails to render. There might be no way around this, but it would be nice to not have to explicitly have to give instructions to go and accept the SSL certificate in our READMEs for samples and stuff.

**Comment by engreimor** [comment]
the support for local development is currently horrible, I hope microsoft fellows work this out.

**Comment by engreimor** [comment]
i was stuck for about an hour with this. The only workout was to export the stub certificate created by gulp to a file (using chrome/export certificate) and manually registering the .cer file to the system. Additionally I created and shared a folder to myself (yeah, that is awkward), to put the manifest.xml generated by generator. That was the only way I figured out to the addins to show up on menu, since I have no office sharepoint 365 nor azure accounts.

Hope it helps somebody.

**Comment by martellaj** [comment]
We're talking about 2 different things. I'm talking about serving apps on localhost for Outlook add-ins. No need to export any certs there. @andrewconnell, any ideas? Would be nice to have a better solution before AngularConnect (if even possible).

**Comment by andrewconnell** [comment]
Nope... no way around this without buying a legit cert that I'm aware of. Office won't load addins from non-HTTP endpoints... it will only load from HTTPS. The only way to do this is to have a cert that your browser trusts. The easiest way to do this is to use self-signed certs, but the cert isn't in your trusted cert chain so the browser doesn't see it as legit. 

The other option would be for a developer to procure a legit cert from a trusted root authority (Verisign, GoDaddy, etc) because they will already be trusted by your machine. However, to run it local you need to tweak the equiv `hosts` file to hijack the request for the legit domain -> localhost and start the site there.

On the Windows dev world, you VS does this for you the first time you start a site on HTTPS, VS creates the self signed cert & trusts it on your machine (prompting you both times). But on OSX, you need to do it manually (unless someone can write a script to automate it).

The good news is once you do this one time with a cert, you should be good for all projects across the life of the cert. We chose to use a specific NPM module because it includes certs so all projects created using this generator will use the same cert... thus once you do this the first time on a machine, you don't have to do it again.

**Comment by martellaj** [comment]
That's what I assumed, but figured I'd call it out and hope for the best. Thanks for the informed response.
