### ISSUE TITLE
Outlook Generator Office TaskPane Not showing

### ISSUE THREAD

**Issue by MartinDawson** [OfficeDev/generator-office#708]
# Prerequisites

Please answer the following questions before submitting an issue. 
**YOU MAY DELETE THE PREREQUISITES SECTION.**
- [x] I am running the latest version of Node and the tools
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

# Expected behavior
TaskPane contoso app is visible and can be loaded in.

# Current behavior

![image](https://user-images.githubusercontent.com/15030491/170832486-4565893f-48f1-4626-99c6-6adbaa6af10e.png)
![image](https://user-images.githubusercontent.com/15030491/170832527-cd1b16f6-9346-4d12-b9f2-2f00cb4411e9.png)
![image](https://user-images.githubusercontent.com/15030491/170832515-a0cc2d07-0e2f-4183-9a00-b67bcc96c6c7.png)

You can see it that it looks like npm start is working but the add-in for contoso is not showing in the taskpane.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

Tried with both a react and javascript app. Same issue.

Just `npm start`

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System: Windows 10
* Node version: 16.15.0
* Office version: Version 2102 Microsoft 365 bundle
* Tool version: ??

**Comment by millerds** [comment]
It's more than just 'npm start'.  Based you your screenshots I can see that the dev server was started before 'npm start' was run and so that part was skipped by the start command.  

The second image shows that the dev server has started and is ready to serve up content . . . but that won't be needed until you actually start the add-in . . . which you can't until it's loaded.  Which narrows it down to the manifest and the version of Office.

Are you able to manually side load the add-in using these instructions? https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/sideload-outlook-add-ins-for-testing?tabs=windows
