### ISSUE TITLE
Outlook Addin created using yo office get disabled after selecting multiple emails.

### ISSUE THREAD

**Issue by vchaudhari2912** [OfficeDev/generator-office#768]
# Prerequisites

Please answer the following questions before submitting an issue. 
**YOU MAY DELETE THE PREREQUISITES SECTION.**
- [yes ] I am running the latest version of Node and the tools
- [ yes] I checked the documentation and found no answer
- [ yes] I checked to make sure that this issue has not already been filed

# Expected behavior

Addin should be enabled when multiple email selected. (Working fine for single email selected)

# Current behavior

When single email selected, My adding enabled and I can able to use it. Once multiple email selected it get disabled

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

Create project using Yo office,
install addin in outlook

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System: MacOs
* Node version: 16.19

**Comment by millerds** [comment]
The project created by 'yo office' is a simple task pane for an individual item.  You can looks at the documentation at https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/item-multi-select to see how to change it to support multi select.  Note that multi select support is only in preview on Windows right now.  More work is needed in order to finish it and extend it to Mac.

**Comment by vchaudhari2912** [comment]
Is there any way then I can get list of emails on the task pane?

**Comment by millerds** [comment]
The office.js API provides access to the currently selected item and it properties.

https://learn.microsoft.com/en-us/javascript/api/requirement-sets/outlook/requirement-set-1.11/office.context.mailbox.item?view=powerpoint-js-preview
