### ISSUE TITLE
Why is Angular not an option in "Choose a Framework"? 

### ISSUE THREAD

**Issue by Ravi-Royal-143** [OfficeDev/generator-office#802]
command used: yo office
I checked the documentation and not able to found the answer.

**Comment by AlexJerabek** [comment]
Hi @Ravi-Royal-143,

We used to have an Angular option for yo office, but it fell out of date. As noted in [this issue](https://github.com/OfficeDev/Office-Addin-TaskPane-Angular/issues/113), we decided it was better to remove the Angular template than promote something with bad patterns. 

Our guidance for using Angular with Office Add-ins can be found here: https://learn.microsoft.com/en-us/office/dev/add-ins/develop/add-ins-with-angular2. You can create a feature request in the [M365 Tech Community](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform) for an Angular yo office option. That will help us prioritize our resources if the idea gains traction in the community.

Since there's not an action to take here, I'm going to close this issue.
