### ISSUE TITLE
No Hot-Reloading When Developing Custom Excel Functions

### ISSUE THREAD

**Issue by alariej** [OfficeDev/generator-office#846]
# Expected behavior

When I launch the development script with `npm run start:desktop`, edit the source code of an Excel function, and then save the `functions.ts` file, I expect to see the updated result of the function in the Excel spreadsheet.

# Current behavior

The function result does not update. The only way I found to debug the project is to use `npm run build`, then `npm run dev-server`, open a spreadsheet, load the add-in, and re-compile, then close + re-open the spreadsheet for every source code change. Isn't there a better way to debug?

# Context

I followed this tutorial: https://learn.microsoft.com/en-us/office/dev/add-ins/quickstarts/excel-custom-functions-quickstart?tabs=excel-windows

* Operating System: Windows 11
* Node version: v16.15.1
* Office version: Office 365
* Tool version: VSCode

**Comment by millerds** [comment]
The Custom Functions javascript runtime does not support the modern syntax injected into the functions file by webpack.  As a result, webpack is setup to serve the file directly from the dist folder instead of from memory (where the injection happens) and the manifest is set to pull from that URL.  You have to run the build step in order to get an updated functions file and you have to restart Excel to pick up that change (the server can actually stay running).

If you use the shared runtime for Custom Functions then it's using webview2 for the runtime which does support the syntax and thus supports the hot reloading.

**Comment by alariej** [comment]
Thanks for coming back. Will check if I can use the shared runtime in my project.
