### ISSUE TITLE
Add reference to /typings/tsd.d.ts in .js files

### ISSUE THREAD

**Issue by waldekmastykarz** [OfficeDev/generator-office#86]
Generated projects have the **tsd.json** file setup with references to Angular and Office typings. It would be helpful to include the reference to the **/typings/tsd.d.ts** file in all .js files so that developers can benefit of intellisense even if they're coding in plain JavaScript.

**Comment by andrewconnell** [comment]
Actually what we need is to add a `tsconfig.json` to the root of the project that's created because editors will see that and automatically load all `*.ts` and `*.d.ts` files into memory so you don't have to do it. I thought we did add it... but looks like not... I can do this as I'm adding working on a bug fix update this weekend.

**Comment by waldekmastykarz** [comment]
Cool! Thanks!
