### ISSUE TITLE
Localhost SSL certificates - install by permission

### ISSUE THREAD

**Issue by CodeMoggy** [OfficeDev/generator-office#96]
The user experience when developing locally at https://localhost:8443 is not good due to certificate errors. Could the creation and install of a self-certificate be included as part of the yo office wizard - the user would need to confirm that the certificate can be installed in their trusted authority store, it should be off by default.

**Comment by andrewconnell** [comment]
We looked into it... This isn't as easy as it sounds. Anything like this really needs to work across all platforms as this is an xplat solution. The gulp plugin we take a dependency on already has a cert that you can trust once on a machine and you're good. The docs include instructions on how to do this. 

Creating a self signed cert for every addin is not an approach we want to promote... One self signed cert per dev machine works... And since the plugin already includes that, we're good on the creation.

If you want to take the job on to create a script that will trust this on all three platforms we'd appreciate it!
